//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace PDFEmailServiceUFMS.RDLC {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("rptDSunitr004v1")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class rptDSunitr004v1 : global::System.Data.DataSet {
        
        private rptDTunitr004v1DataTable tablerptDTunitr004v1;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public rptDSunitr004v1() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [System.ObsoleteAttribute("This API supports obsolete formatter-based serialization. It should not be called" +
            " or extended by application code.", DiagnosticId="SYSLIB0051")]
        protected rptDSunitr004v1(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["rptDTunitr004v1"] != null)) {
                    base.Tables.Add(new rptDTunitr004v1DataTable(ds.Tables["rptDTunitr004v1"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public rptDTunitr004v1DataTable rptDTunitr004v1 {
            get {
                return this.tablerptDTunitr004v1;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            rptDSunitr004v1 cln = ((rptDSunitr004v1)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["rptDTunitr004v1"] != null)) {
                    base.Tables.Add(new rptDTunitr004v1DataTable(ds.Tables["rptDTunitr004v1"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tablerptDTunitr004v1 = ((rptDTunitr004v1DataTable)(base.Tables["rptDTunitr004v1"]));
            if ((initTable == true)) {
                if ((this.tablerptDTunitr004v1 != null)) {
                    this.tablerptDTunitr004v1.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private void InitClass() {
            this.DataSetName = "rptDSunitr004v1";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/rptDSunitr004v1.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tablerptDTunitr004v1 = new rptDTunitr004v1DataTable();
            base.Tables.Add(this.tablerptDTunitr004v1);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private bool ShouldSerializerptDTunitr004v1() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            rptDSunitr004v1 ds = new rptDSunitr004v1();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public delegate void rptDTunitr004v1RowChangeEventHandler(object sender, rptDTunitr004v1RowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class rptDTunitr004v1DataTable : global::System.Data.TypedTableBase<rptDTunitr004v1Row> {
            
            private global::System.Data.DataColumn columnLETTER_NO;
            
            private global::System.Data.DataColumn columnWARRENT_DATE;
            
            private global::System.Data.DataColumn columnREG_BK;
            
            private global::System.Data.DataColumn columnREG_BR;
            
            private global::System.Data.DataColumn columnREG_NO;
            
            private global::System.Data.DataColumn columnNAME;
            
            private global::System.Data.DataColumn columnADDRS1;
            
            private global::System.Data.DataColumn columnADDRS2;
            
            private global::System.Data.DataColumn columnCITY;
            
            private global::System.Data.DataColumn columnBALANCE;
            
            private global::System.Data.DataColumn columnDIVIDEND_RATE;
            
            private global::System.Data.DataColumn columnGROSS_DIVIDEND;
            
            private global::System.Data.DataColumn columnTAX;
            
            private global::System.Data.DataColumn columnTAX_DEDUCTION;
            
            private global::System.Data.DataColumn columnNET_DIVIDENT;
            
            private global::System.Data.DataColumn columnREGISTRATION_NO_FULL;
            
            private global::System.Data.DataColumn columnINPUT_DATE;
            
            private global::System.Data.DataColumn columnJNT_NAME1;
            
            private global::System.Data.DataColumn columnJNT_NAME2;
            
            private global::System.Data.DataColumn columnJNT_NAME3;
            
            private global::System.Data.DataColumn columnFULL_NAME_ADDRESS;
            
            private global::System.Data.DataColumn columnYEAR_END_DATE;
            
            private global::System.Data.DataColumn columnINVESTMENT_YEAR;
            
            private global::System.Data.DataColumn columnYEAR_END_DATE_STR;
            
            private global::System.Data.DataColumn columnINCOME_TAX_RULE_NAME;
            
            private global::System.Data.DataColumn columnWARRENT_DATE_STR;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public rptDTunitr004v1DataTable() {
                this.TableName = "rptDTunitr004v1";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal rptDTunitr004v1DataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            [System.ObsoleteAttribute("This API supports obsolete formatter-based serialization. It should not be called" +
                " or extended by application code.", DiagnosticId="SYSLIB0051")]
            protected rptDTunitr004v1DataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn LETTER_NOColumn {
                get {
                    return this.columnLETTER_NO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn WARRENT_DATEColumn {
                get {
                    return this.columnWARRENT_DATE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn REG_BKColumn {
                get {
                    return this.columnREG_BK;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn REG_BRColumn {
                get {
                    return this.columnREG_BR;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn REG_NOColumn {
                get {
                    return this.columnREG_NO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn NAMEColumn {
                get {
                    return this.columnNAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn ADDRS1Column {
                get {
                    return this.columnADDRS1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn ADDRS2Column {
                get {
                    return this.columnADDRS2;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn CITYColumn {
                get {
                    return this.columnCITY;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn BALANCEColumn {
                get {
                    return this.columnBALANCE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn DIVIDEND_RATEColumn {
                get {
                    return this.columnDIVIDEND_RATE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn GROSS_DIVIDENDColumn {
                get {
                    return this.columnGROSS_DIVIDEND;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn TAXColumn {
                get {
                    return this.columnTAX;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn TAX_DEDUCTIONColumn {
                get {
                    return this.columnTAX_DEDUCTION;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn NET_DIVIDENTColumn {
                get {
                    return this.columnNET_DIVIDENT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn REGISTRATION_NO_FULLColumn {
                get {
                    return this.columnREGISTRATION_NO_FULL;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn INPUT_DATEColumn {
                get {
                    return this.columnINPUT_DATE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn JNT_NAME1Column {
                get {
                    return this.columnJNT_NAME1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn JNT_NAME2Column {
                get {
                    return this.columnJNT_NAME2;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn JNT_NAME3Column {
                get {
                    return this.columnJNT_NAME3;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn FULL_NAME_ADDRESSColumn {
                get {
                    return this.columnFULL_NAME_ADDRESS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn YEAR_END_DATEColumn {
                get {
                    return this.columnYEAR_END_DATE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn INVESTMENT_YEARColumn {
                get {
                    return this.columnINVESTMENT_YEAR;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn YEAR_END_DATE_STRColumn {
                get {
                    return this.columnYEAR_END_DATE_STR;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn INCOME_TAX_RULE_NAMEColumn {
                get {
                    return this.columnINCOME_TAX_RULE_NAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn WARRENT_DATE_STRColumn {
                get {
                    return this.columnWARRENT_DATE_STR;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public rptDTunitr004v1Row this[int index] {
                get {
                    return ((rptDTunitr004v1Row)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event rptDTunitr004v1RowChangeEventHandler rptDTunitr004v1RowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event rptDTunitr004v1RowChangeEventHandler rptDTunitr004v1RowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event rptDTunitr004v1RowChangeEventHandler rptDTunitr004v1RowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event rptDTunitr004v1RowChangeEventHandler rptDTunitr004v1RowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void AddrptDTunitr004v1Row(rptDTunitr004v1Row row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public rptDTunitr004v1Row AddrptDTunitr004v1Row(
                        string LETTER_NO, 
                        string WARRENT_DATE, 
                        string REG_BK, 
                        string REG_BR, 
                        string REG_NO, 
                        string NAME, 
                        string ADDRS1, 
                        string ADDRS2, 
                        string CITY, 
                        string BALANCE, 
                        string DIVIDEND_RATE, 
                        string GROSS_DIVIDEND, 
                        string TAX, 
                        string TAX_DEDUCTION, 
                        string NET_DIVIDENT, 
                        string REGISTRATION_NO_FULL, 
                        string INPUT_DATE, 
                        string JNT_NAME1, 
                        string JNT_NAME2, 
                        string JNT_NAME3, 
                        string FULL_NAME_ADDRESS, 
                        string YEAR_END_DATE, 
                        string INVESTMENT_YEAR, 
                        string YEAR_END_DATE_STR, 
                        string INCOME_TAX_RULE_NAME, 
                        string WARRENT_DATE_STR) {
                rptDTunitr004v1Row rowrptDTunitr004v1Row = ((rptDTunitr004v1Row)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        LETTER_NO,
                        WARRENT_DATE,
                        REG_BK,
                        REG_BR,
                        REG_NO,
                        NAME,
                        ADDRS1,
                        ADDRS2,
                        CITY,
                        BALANCE,
                        DIVIDEND_RATE,
                        GROSS_DIVIDEND,
                        TAX,
                        TAX_DEDUCTION,
                        NET_DIVIDENT,
                        REGISTRATION_NO_FULL,
                        INPUT_DATE,
                        JNT_NAME1,
                        JNT_NAME2,
                        JNT_NAME3,
                        FULL_NAME_ADDRESS,
                        YEAR_END_DATE,
                        INVESTMENT_YEAR,
                        YEAR_END_DATE_STR,
                        INCOME_TAX_RULE_NAME,
                        WARRENT_DATE_STR};
                rowrptDTunitr004v1Row.ItemArray = columnValuesArray;
                this.Rows.Add(rowrptDTunitr004v1Row);
                return rowrptDTunitr004v1Row;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                rptDTunitr004v1DataTable cln = ((rptDTunitr004v1DataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new rptDTunitr004v1DataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal void InitVars() {
                this.columnLETTER_NO = base.Columns["LETTER_NO"];
                this.columnWARRENT_DATE = base.Columns["WARRENT_DATE"];
                this.columnREG_BK = base.Columns["REG_BK"];
                this.columnREG_BR = base.Columns["REG_BR"];
                this.columnREG_NO = base.Columns["REG_NO"];
                this.columnNAME = base.Columns["NAME"];
                this.columnADDRS1 = base.Columns["ADDRS1"];
                this.columnADDRS2 = base.Columns["ADDRS2"];
                this.columnCITY = base.Columns["CITY"];
                this.columnBALANCE = base.Columns["BALANCE"];
                this.columnDIVIDEND_RATE = base.Columns["DIVIDEND_RATE"];
                this.columnGROSS_DIVIDEND = base.Columns["GROSS_DIVIDEND"];
                this.columnTAX = base.Columns["TAX"];
                this.columnTAX_DEDUCTION = base.Columns["TAX_DEDUCTION"];
                this.columnNET_DIVIDENT = base.Columns["NET_DIVIDENT"];
                this.columnREGISTRATION_NO_FULL = base.Columns["REGISTRATION_NO_FULL"];
                this.columnINPUT_DATE = base.Columns["INPUT_DATE"];
                this.columnJNT_NAME1 = base.Columns["JNT_NAME1"];
                this.columnJNT_NAME2 = base.Columns["JNT_NAME2"];
                this.columnJNT_NAME3 = base.Columns["JNT_NAME3"];
                this.columnFULL_NAME_ADDRESS = base.Columns["FULL_NAME_ADDRESS"];
                this.columnYEAR_END_DATE = base.Columns["YEAR_END_DATE"];
                this.columnINVESTMENT_YEAR = base.Columns["INVESTMENT_YEAR"];
                this.columnYEAR_END_DATE_STR = base.Columns["YEAR_END_DATE_STR"];
                this.columnINCOME_TAX_RULE_NAME = base.Columns["INCOME_TAX_RULE_NAME"];
                this.columnWARRENT_DATE_STR = base.Columns["WARRENT_DATE_STR"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            private void InitClass() {
                this.columnLETTER_NO = new global::System.Data.DataColumn("LETTER_NO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnLETTER_NO);
                this.columnWARRENT_DATE = new global::System.Data.DataColumn("WARRENT_DATE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnWARRENT_DATE);
                this.columnREG_BK = new global::System.Data.DataColumn("REG_BK", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnREG_BK);
                this.columnREG_BR = new global::System.Data.DataColumn("REG_BR", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnREG_BR);
                this.columnREG_NO = new global::System.Data.DataColumn("REG_NO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnREG_NO);
                this.columnNAME = new global::System.Data.DataColumn("NAME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNAME);
                this.columnADDRS1 = new global::System.Data.DataColumn("ADDRS1", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnADDRS1);
                this.columnADDRS2 = new global::System.Data.DataColumn("ADDRS2", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnADDRS2);
                this.columnCITY = new global::System.Data.DataColumn("CITY", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCITY);
                this.columnBALANCE = new global::System.Data.DataColumn("BALANCE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBALANCE);
                this.columnDIVIDEND_RATE = new global::System.Data.DataColumn("DIVIDEND_RATE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDIVIDEND_RATE);
                this.columnGROSS_DIVIDEND = new global::System.Data.DataColumn("GROSS_DIVIDEND", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnGROSS_DIVIDEND);
                this.columnTAX = new global::System.Data.DataColumn("TAX", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTAX);
                this.columnTAX_DEDUCTION = new global::System.Data.DataColumn("TAX_DEDUCTION", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTAX_DEDUCTION);
                this.columnNET_DIVIDENT = new global::System.Data.DataColumn("NET_DIVIDENT", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNET_DIVIDENT);
                this.columnREGISTRATION_NO_FULL = new global::System.Data.DataColumn("REGISTRATION_NO_FULL", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnREGISTRATION_NO_FULL);
                this.columnINPUT_DATE = new global::System.Data.DataColumn("INPUT_DATE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnINPUT_DATE);
                this.columnJNT_NAME1 = new global::System.Data.DataColumn("JNT_NAME1", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnJNT_NAME1);
                this.columnJNT_NAME2 = new global::System.Data.DataColumn("JNT_NAME2", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnJNT_NAME2);
                this.columnJNT_NAME3 = new global::System.Data.DataColumn("JNT_NAME3", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnJNT_NAME3);
                this.columnFULL_NAME_ADDRESS = new global::System.Data.DataColumn("FULL_NAME_ADDRESS", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFULL_NAME_ADDRESS);
                this.columnYEAR_END_DATE = new global::System.Data.DataColumn("YEAR_END_DATE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnYEAR_END_DATE);
                this.columnINVESTMENT_YEAR = new global::System.Data.DataColumn("INVESTMENT_YEAR", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnINVESTMENT_YEAR);
                this.columnYEAR_END_DATE_STR = new global::System.Data.DataColumn("YEAR_END_DATE_STR", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnYEAR_END_DATE_STR);
                this.columnINCOME_TAX_RULE_NAME = new global::System.Data.DataColumn("INCOME_TAX_RULE_NAME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnINCOME_TAX_RULE_NAME);
                this.columnWARRENT_DATE_STR = new global::System.Data.DataColumn("WARRENT_DATE_STR", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnWARRENT_DATE_STR);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public rptDTunitr004v1Row NewrptDTunitr004v1Row() {
                return ((rptDTunitr004v1Row)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new rptDTunitr004v1Row(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(rptDTunitr004v1Row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.rptDTunitr004v1RowChanged != null)) {
                    this.rptDTunitr004v1RowChanged(this, new rptDTunitr004v1RowChangeEvent(((rptDTunitr004v1Row)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.rptDTunitr004v1RowChanging != null)) {
                    this.rptDTunitr004v1RowChanging(this, new rptDTunitr004v1RowChangeEvent(((rptDTunitr004v1Row)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.rptDTunitr004v1RowDeleted != null)) {
                    this.rptDTunitr004v1RowDeleted(this, new rptDTunitr004v1RowChangeEvent(((rptDTunitr004v1Row)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.rptDTunitr004v1RowDeleting != null)) {
                    this.rptDTunitr004v1RowDeleting(this, new rptDTunitr004v1RowChangeEvent(((rptDTunitr004v1Row)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void RemoverptDTunitr004v1Row(rptDTunitr004v1Row row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                rptDSunitr004v1 ds = new rptDSunitr004v1();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "rptDTunitr004v1DataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class rptDTunitr004v1Row : global::System.Data.DataRow {
            
            private rptDTunitr004v1DataTable tablerptDTunitr004v1;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal rptDTunitr004v1Row(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tablerptDTunitr004v1 = ((rptDTunitr004v1DataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string LETTER_NO {
                get {
                    try {
                        return ((string)(this[this.tablerptDTunitr004v1.LETTER_NOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'LETTER_NO\' in table \'rptDTunitr004v1\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablerptDTunitr004v1.LETTER_NOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string WARRENT_DATE {
                get {
                    try {
                        return ((string)(this[this.tablerptDTunitr004v1.WARRENT_DATEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'WARRENT_DATE\' in table \'rptDTunitr004v1\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablerptDTunitr004v1.WARRENT_DATEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string REG_BK {
                get {
                    try {
                        return ((string)(this[this.tablerptDTunitr004v1.REG_BKColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'REG_BK\' in table \'rptDTunitr004v1\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablerptDTunitr004v1.REG_BKColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string REG_BR {
                get {
                    try {
                        return ((string)(this[this.tablerptDTunitr004v1.REG_BRColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'REG_BR\' in table \'rptDTunitr004v1\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablerptDTunitr004v1.REG_BRColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string REG_NO {
                get {
                    try {
                        return ((string)(this[this.tablerptDTunitr004v1.REG_NOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'REG_NO\' in table \'rptDTunitr004v1\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablerptDTunitr004v1.REG_NOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string NAME {
                get {
                    try {
                        return ((string)(this[this.tablerptDTunitr004v1.NAMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NAME\' in table \'rptDTunitr004v1\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablerptDTunitr004v1.NAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string ADDRS1 {
                get {
                    try {
                        return ((string)(this[this.tablerptDTunitr004v1.ADDRS1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ADDRS1\' in table \'rptDTunitr004v1\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablerptDTunitr004v1.ADDRS1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string ADDRS2 {
                get {
                    try {
                        return ((string)(this[this.tablerptDTunitr004v1.ADDRS2Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ADDRS2\' in table \'rptDTunitr004v1\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablerptDTunitr004v1.ADDRS2Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string CITY {
                get {
                    try {
                        return ((string)(this[this.tablerptDTunitr004v1.CITYColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CITY\' in table \'rptDTunitr004v1\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablerptDTunitr004v1.CITYColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string BALANCE {
                get {
                    try {
                        return ((string)(this[this.tablerptDTunitr004v1.BALANCEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BALANCE\' in table \'rptDTunitr004v1\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablerptDTunitr004v1.BALANCEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string DIVIDEND_RATE {
                get {
                    try {
                        return ((string)(this[this.tablerptDTunitr004v1.DIVIDEND_RATEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DIVIDEND_RATE\' in table \'rptDTunitr004v1\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablerptDTunitr004v1.DIVIDEND_RATEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string GROSS_DIVIDEND {
                get {
                    try {
                        return ((string)(this[this.tablerptDTunitr004v1.GROSS_DIVIDENDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'GROSS_DIVIDEND\' in table \'rptDTunitr004v1\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablerptDTunitr004v1.GROSS_DIVIDENDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string TAX {
                get {
                    try {
                        return ((string)(this[this.tablerptDTunitr004v1.TAXColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TAX\' in table \'rptDTunitr004v1\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablerptDTunitr004v1.TAXColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string TAX_DEDUCTION {
                get {
                    try {
                        return ((string)(this[this.tablerptDTunitr004v1.TAX_DEDUCTIONColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TAX_DEDUCTION\' in table \'rptDTunitr004v1\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablerptDTunitr004v1.TAX_DEDUCTIONColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string NET_DIVIDENT {
                get {
                    try {
                        return ((string)(this[this.tablerptDTunitr004v1.NET_DIVIDENTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NET_DIVIDENT\' in table \'rptDTunitr004v1\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablerptDTunitr004v1.NET_DIVIDENTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string REGISTRATION_NO_FULL {
                get {
                    try {
                        return ((string)(this[this.tablerptDTunitr004v1.REGISTRATION_NO_FULLColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'REGISTRATION_NO_FULL\' in table \'rptDTunitr004v1\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tablerptDTunitr004v1.REGISTRATION_NO_FULLColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string INPUT_DATE {
                get {
                    try {
                        return ((string)(this[this.tablerptDTunitr004v1.INPUT_DATEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'INPUT_DATE\' in table \'rptDTunitr004v1\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablerptDTunitr004v1.INPUT_DATEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string JNT_NAME1 {
                get {
                    try {
                        return ((string)(this[this.tablerptDTunitr004v1.JNT_NAME1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'JNT_NAME1\' in table \'rptDTunitr004v1\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablerptDTunitr004v1.JNT_NAME1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string JNT_NAME2 {
                get {
                    try {
                        return ((string)(this[this.tablerptDTunitr004v1.JNT_NAME2Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'JNT_NAME2\' in table \'rptDTunitr004v1\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablerptDTunitr004v1.JNT_NAME2Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string JNT_NAME3 {
                get {
                    try {
                        return ((string)(this[this.tablerptDTunitr004v1.JNT_NAME3Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'JNT_NAME3\' in table \'rptDTunitr004v1\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablerptDTunitr004v1.JNT_NAME3Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string FULL_NAME_ADDRESS {
                get {
                    try {
                        return ((string)(this[this.tablerptDTunitr004v1.FULL_NAME_ADDRESSColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'FULL_NAME_ADDRESS\' in table \'rptDTunitr004v1\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablerptDTunitr004v1.FULL_NAME_ADDRESSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string YEAR_END_DATE {
                get {
                    try {
                        return ((string)(this[this.tablerptDTunitr004v1.YEAR_END_DATEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'YEAR_END_DATE\' in table \'rptDTunitr004v1\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablerptDTunitr004v1.YEAR_END_DATEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string INVESTMENT_YEAR {
                get {
                    try {
                        return ((string)(this[this.tablerptDTunitr004v1.INVESTMENT_YEARColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'INVESTMENT_YEAR\' in table \'rptDTunitr004v1\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablerptDTunitr004v1.INVESTMENT_YEARColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string YEAR_END_DATE_STR {
                get {
                    try {
                        return ((string)(this[this.tablerptDTunitr004v1.YEAR_END_DATE_STRColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'YEAR_END_DATE_STR\' in table \'rptDTunitr004v1\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablerptDTunitr004v1.YEAR_END_DATE_STRColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string INCOME_TAX_RULE_NAME {
                get {
                    try {
                        return ((string)(this[this.tablerptDTunitr004v1.INCOME_TAX_RULE_NAMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'INCOME_TAX_RULE_NAME\' in table \'rptDTunitr004v1\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tablerptDTunitr004v1.INCOME_TAX_RULE_NAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string WARRENT_DATE_STR {
                get {
                    try {
                        return ((string)(this[this.tablerptDTunitr004v1.WARRENT_DATE_STRColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'WARRENT_DATE_STR\' in table \'rptDTunitr004v1\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablerptDTunitr004v1.WARRENT_DATE_STRColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsLETTER_NONull() {
                return this.IsNull(this.tablerptDTunitr004v1.LETTER_NOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetLETTER_NONull() {
                this[this.tablerptDTunitr004v1.LETTER_NOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsWARRENT_DATENull() {
                return this.IsNull(this.tablerptDTunitr004v1.WARRENT_DATEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetWARRENT_DATENull() {
                this[this.tablerptDTunitr004v1.WARRENT_DATEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsREG_BKNull() {
                return this.IsNull(this.tablerptDTunitr004v1.REG_BKColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetREG_BKNull() {
                this[this.tablerptDTunitr004v1.REG_BKColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsREG_BRNull() {
                return this.IsNull(this.tablerptDTunitr004v1.REG_BRColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetREG_BRNull() {
                this[this.tablerptDTunitr004v1.REG_BRColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsREG_NONull() {
                return this.IsNull(this.tablerptDTunitr004v1.REG_NOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetREG_NONull() {
                this[this.tablerptDTunitr004v1.REG_NOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsNAMENull() {
                return this.IsNull(this.tablerptDTunitr004v1.NAMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetNAMENull() {
                this[this.tablerptDTunitr004v1.NAMEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsADDRS1Null() {
                return this.IsNull(this.tablerptDTunitr004v1.ADDRS1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetADDRS1Null() {
                this[this.tablerptDTunitr004v1.ADDRS1Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsADDRS2Null() {
                return this.IsNull(this.tablerptDTunitr004v1.ADDRS2Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetADDRS2Null() {
                this[this.tablerptDTunitr004v1.ADDRS2Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsCITYNull() {
                return this.IsNull(this.tablerptDTunitr004v1.CITYColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetCITYNull() {
                this[this.tablerptDTunitr004v1.CITYColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsBALANCENull() {
                return this.IsNull(this.tablerptDTunitr004v1.BALANCEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetBALANCENull() {
                this[this.tablerptDTunitr004v1.BALANCEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsDIVIDEND_RATENull() {
                return this.IsNull(this.tablerptDTunitr004v1.DIVIDEND_RATEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetDIVIDEND_RATENull() {
                this[this.tablerptDTunitr004v1.DIVIDEND_RATEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsGROSS_DIVIDENDNull() {
                return this.IsNull(this.tablerptDTunitr004v1.GROSS_DIVIDENDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetGROSS_DIVIDENDNull() {
                this[this.tablerptDTunitr004v1.GROSS_DIVIDENDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsTAXNull() {
                return this.IsNull(this.tablerptDTunitr004v1.TAXColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetTAXNull() {
                this[this.tablerptDTunitr004v1.TAXColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsTAX_DEDUCTIONNull() {
                return this.IsNull(this.tablerptDTunitr004v1.TAX_DEDUCTIONColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetTAX_DEDUCTIONNull() {
                this[this.tablerptDTunitr004v1.TAX_DEDUCTIONColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsNET_DIVIDENTNull() {
                return this.IsNull(this.tablerptDTunitr004v1.NET_DIVIDENTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetNET_DIVIDENTNull() {
                this[this.tablerptDTunitr004v1.NET_DIVIDENTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsREGISTRATION_NO_FULLNull() {
                return this.IsNull(this.tablerptDTunitr004v1.REGISTRATION_NO_FULLColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetREGISTRATION_NO_FULLNull() {
                this[this.tablerptDTunitr004v1.REGISTRATION_NO_FULLColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsINPUT_DATENull() {
                return this.IsNull(this.tablerptDTunitr004v1.INPUT_DATEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetINPUT_DATENull() {
                this[this.tablerptDTunitr004v1.INPUT_DATEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsJNT_NAME1Null() {
                return this.IsNull(this.tablerptDTunitr004v1.JNT_NAME1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetJNT_NAME1Null() {
                this[this.tablerptDTunitr004v1.JNT_NAME1Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsJNT_NAME2Null() {
                return this.IsNull(this.tablerptDTunitr004v1.JNT_NAME2Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetJNT_NAME2Null() {
                this[this.tablerptDTunitr004v1.JNT_NAME2Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsJNT_NAME3Null() {
                return this.IsNull(this.tablerptDTunitr004v1.JNT_NAME3Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetJNT_NAME3Null() {
                this[this.tablerptDTunitr004v1.JNT_NAME3Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsFULL_NAME_ADDRESSNull() {
                return this.IsNull(this.tablerptDTunitr004v1.FULL_NAME_ADDRESSColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetFULL_NAME_ADDRESSNull() {
                this[this.tablerptDTunitr004v1.FULL_NAME_ADDRESSColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsYEAR_END_DATENull() {
                return this.IsNull(this.tablerptDTunitr004v1.YEAR_END_DATEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetYEAR_END_DATENull() {
                this[this.tablerptDTunitr004v1.YEAR_END_DATEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsINVESTMENT_YEARNull() {
                return this.IsNull(this.tablerptDTunitr004v1.INVESTMENT_YEARColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetINVESTMENT_YEARNull() {
                this[this.tablerptDTunitr004v1.INVESTMENT_YEARColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsYEAR_END_DATE_STRNull() {
                return this.IsNull(this.tablerptDTunitr004v1.YEAR_END_DATE_STRColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetYEAR_END_DATE_STRNull() {
                this[this.tablerptDTunitr004v1.YEAR_END_DATE_STRColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsINCOME_TAX_RULE_NAMENull() {
                return this.IsNull(this.tablerptDTunitr004v1.INCOME_TAX_RULE_NAMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetINCOME_TAX_RULE_NAMENull() {
                this[this.tablerptDTunitr004v1.INCOME_TAX_RULE_NAMEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsWARRENT_DATE_STRNull() {
                return this.IsNull(this.tablerptDTunitr004v1.WARRENT_DATE_STRColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetWARRENT_DATE_STRNull() {
                this[this.tablerptDTunitr004v1.WARRENT_DATE_STRColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public class rptDTunitr004v1RowChangeEvent : global::System.EventArgs {
            
            private rptDTunitr004v1Row eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public rptDTunitr004v1RowChangeEvent(rptDTunitr004v1Row row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public rptDTunitr004v1Row Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591